### PR TITLE
standal-ce-nginx

### PR DESCRIPTION
**Pull request by realStandal**
Guess it's giving you everything again, lol

### CODE REVIEW

**Review by jeliasson — APPROVED** [review]

**Comment by jeliasson** [comment]
@realStandal hehe :)

Add the `main` branch to build next time aswell, as then we can build everything at once when we e.g. update RedwoodJS or change a baseline. 

Looks like you got some good results with the api! 🙏

**Comment by realStandal** [comment]
@jeliasson Nicer to see the base-Redwood size too. I was building the app I have been - which has a few dependencies of its own - using 0.37 and it's lower too, around 360 I want to guess.

GitHub does the builds in parallel so my shared base stage isn't doing too much here, does help locally though so..

**Comment by realStandal** [comment]
And what are some things we're thinking will go into the "Basic Installation"?

The biggest blocker I can see is the need to be load balanced, but that could be pretty easily overcame with a redirect config in the default `nginx.conf` and a note about it's purpose. Unless even that is falling out of the basic realm lol

Were there other things you had in mind? I'm of the mind "basic" is the most desired option.

**Comment by jeliasson** [comment]
@realStandal I guess we need to define that as we go, but one can imagine we define something like this;

* Basic: One container serving both api and web
* Medium: One container serving api and one serving web (`yarn rw serve web` vs nginx/caddy with more options)
* Advanced: As medium, but examples with a separate container/proxy on the edge and/or CDN deployment for the web
* Expert: At this point we're talking about high availability in various scenarios.

For now it's just a dummy matrix, and I suggest we just update/make suggestions as we go.

**Pull request merged**
